export enum AppEventType {
  CLICKED_ON_NOTIFICATION = 'CLICKED_ON_NOTIFICATION',
  SOCKET_EVENT = 'SOCKET_EVENT',
  TOGGLE_EVENT = 'TOGGLE_EVENT',
  CHECKBOX_EVENT = 'CHECKBOX_EVENT',
  CLICKED_ON_LOCALE_DROPDOWN = 'CLICKED_ON_LOCALE_DROPDOWN',
  ACCORDION_EVENT_INIT = 'ACCORDION_EVENT_INIT',
  ACCORDION_EVENT = 'ACCORDION_EVENT',
  SELECTED_PAGE = 'SELECTED_PAGE',
  DROPDOWN_EVENT = 'DROPDOWN_EVENT',
  SELECTED_LOCALE_EVENT = 'SELECTED_LOCALE_EVENT',
  AVAILABLE_LOCALES_EVENT = 'AVAILABLE_LOCALES_EVENT',
}
